version: 2.1

orbs:
  ruby: circleci/ruby@1.1

jobs:
  build:
    docker:
      - image: circleci/ruby:3.2.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: bundle install --path=vendor/bundle

      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database setup
          command: bundle exec rake db:create db:schema:load RAILS_ENV=test

      - run:
          name: Run RSpec tests
          command: bundle exec rspec

  deploy:
    docker:
      - image: circleci/ruby:3.2.2

    working_directory: ~/repo

    steps:
      - checkout

      # Add deployment steps here

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
