default: &default
  adapter: postgresql
  encoding: unicode
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: inventorycars

production:
  <<: *default
  database: inventorycars



# pg_restore --verbose --clean --no-acl --no-owner -h localhost -U postgres -d iqglobal dbexport14Dec20232023.sql
# postgres


# development:
#   adapter: postgresql
#   host: db-enterprise-iqgl.cwtkdphmi2yp.us-east-1.rds.amazonaws.com
#   port: 5432
#   encoding: utf8
#   database: iqgl_prod
#   username: postgres
#   password: RAJKAP563&
#   pool: 8